# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad24010c59f2b942f89e3bc2bb3fa41421e955a081aceed17088e74ac798261a76329c653a157eb238102537798b2e3ebc1f3c9071c804f0fece170824f53e08

test:
  secret_key_base: 04db8bc9d2929a0e038a3db8f24c901d5209fdeb7a8ed768adbea3fdd46b0695de26a2d8b5f6b7a504f2b9becd97e2bc22e5fb6424055e5abd62097fc2cd429c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
